---

- name: Deploy nginx
  hosts: webservers
  remote user: runner
  become : yes
  become method: sudo

  tasks :
  — name: Install nginx
    ansible.builtin.apt:
      name: nginx
      state: latest
      update_cache : yes

  — name: Copy index
    ansible.builtin.copy:
      src: ./index.html
      dest: /var/www/html/index.nginx-debian.html
      owner : root
      group : root
      mode: '0666'